### ISSUE TITLE
[RFC]: archive this project

### ISSUE THREAD

**Issue by Ocramius** [laminas/laminas-cache-storage-adapter-zend-server#12]
As discussed internally on slack, we cannot maintain what cannot be tested.

This component relies on internal Zend Server details that are not available (to my current knowledge) within a GitHub Actions setup.

We should therefore move this component to security-only, receiving only very minimal patches.

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | 1.1.0  |
| BC Break?           | No |

**Comment by boesing** [comment]
I wanted to abandon it in https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2021-05-03-TSC-Minutes.md#abandoning-laminas-cache-satellites-part-2 but somehow, we moved on with it due to perforce devs were nominated to maintain laminas-db and thus we were thinking about "outsourcing" this component to them as well.

Since these nominations were reverted after a few months, we are now at the same point as we were back in the days:

There are no maintainers for both this and laminas-db component and thus, I'd be fine with archiving this. We can still un-archiving it if some1 feels to be stepped on his toes.

---

Closing this as "accepted" and immediately archiving it.
